name: Publish

on:
  workflow_dispatch: {}
  release:
    types:
      - created

env:
  PYTHON_VERSION: 3.11

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build and Publish
        env:
          {{REPO_NAME_ALLCAPS}}_VERSION: ${{ github.event.release.tag_name }}
        run: |
          uv build
          uv publish
