name: Test Slow

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Package
        run: |
          pip install -e .[test]

      - name: Test
        run: pytest --slow --cov --cov-report term-missing --cov-fail-under 80 tests/
